conda_forge_output_validation: true
conda_build_tool: rattler-build
bot:
  automerge: false
  inspection: update-grayskull
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
